
#scripts that run after cloning repository
install:
  - cmd: choco install maven -y -f
  - cmd: refreshenv
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  
#to run your custom scripts instead of automatic MSBuild
build_script:
  - mvn clean install site

artifacts:
  - path: 'target\x2fax-*-full.zip'

#environment variables
environment:
  CI: true

#branches to build
branches:
  #whitelist
  only:
    - master
    - production

#Do not build on tags (GitHub and BitBucket)
skip_tags: true

#Maximum number of concurrent jobs for the project
max_jobs: 1

#Build worker image (VM template)
image: Visual Studio 2015

#scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#fetch repository as zip archive
shallow_clone: false

matrix:
  fast_finish: true

#build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86

#build Configuration, i.e. Debug, Release, etc.
#configuration: Release
